[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
anyhow = { version = "1" }
clap = { version = "4", features = ["derive"] }
iced = { git = "https://github.com/pop-os/iced.git", branch = "master", features = [
  "tokio",
  "wayland",
  "winit",
  "image",
] }
serde = { version = "1" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toml = { version = "0.9" }
