[workspace]
resolver = "3"
members = ["shell/*", "plugins/*", "third_party/*"]

[workspace.dependencies]
# shell modules
fs_cli = { path = "shell/fs_cli" }
fs_feature = { path = "shell/fs_feature" }
fs_msg = { path = "shell/fs_msg" }
fs_plugin = { path = "shell/fs_plugin" }
fs_plugin_mgr = { path = "shell/fs_plugin_mgr" }

# plugins
fs_clock = { path = "plugins/fs_clock" }

# third party modules
yadi = { path = "third_party/yadi" }

# others
anyhow = { version = "1" }
chrono = { version = "0.4" }
clap = { version = "4" }
dlopen2 = { version = "0.8" }
hyprland = { version = "0.4.0-beta.3" }
iced = { git = "https://github.com/pop-os/iced.git", branch = "master" }
iced_aw = { version = "0.12" }
libc = { version = "0.2" }
proc-macro2 = { version = "1" }
quote = { version = "1" }
serde = { version = "1" }
starship-battery = { version = "0.10" }
syn = { version = "2" }
thiserror = { version = "2" }
tokio = { version = "1" }
toml = { version = "0.9" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
