[package]
name = "flcs"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
iced = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
